using System.Text.Json;
using FluentAssertions;
using FollowAlpha.LP.Domain.Kernel;
using FollowAlpha.LP.Domain.Primitives;
using Xunit;

namespace FollowAlpha.LP.Domain.Tests.Golden;

/// <summary>
/// The liquidity-math kernel's acceptance contract: every registered case in <c>Golden/fixtures.json</c>
/// (generated by the Elsts Python oracle) must be reproduced by the C# kernel within the documented
/// relative tolerance. The C# kernel converges to the oracle, never the reverse (AGENTS.md hard rule 3).
/// </summary>
public class GoldenLiquidityMathTests
{
    private static readonly JsonDocument Document = LoadDocument();
    private static readonly decimal RelativeTolerance =
        Document.RootElement.GetProperty("relative_tolerance").GetDecimal();

    public static IEnumerable<object[]> Cases()
    {
        foreach (var c in Document.RootElement.GetProperty("cases").EnumerateArray())
        {
            yield return [c.GetProperty("name").GetString()!];
        }
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void Kernel_matches_oracle(string name)
    {
        var c = FindCase(name);
        var inputs = c.GetProperty("inputs");
        var sqrt = c.GetProperty("sqrt");

        var p = Dec(inputs, "p");
        var x = Dec(inputs, "x");
        var y = Dec(inputs, "y");
        var sp = Dec(sqrt, "sp");
        var sa = Dec(sqrt, "sa");
        var sb = Dec(sqrt, "sb");
        var liquidity = Dec(c, "liquidity");

        // L from amounts + range (and the two single-side helpers over the full range).
        Approx(LiquidityMath.GetLiquidity(x, y, sp, sa, sb), liquidity, "liquidity");
        ApproxIf(c, "liquidity0", () => LiquidityMath.GetLiquidity0(x, sa, sb));
        ApproxIf(c, "liquidity1", () => LiquidityMath.GetLiquidity1(y, sa, sb));

        // Amounts from L + price (oracle liquidity fed in to isolate this step).
        ApproxIf(c, "calculate_x", () => LiquidityMath.CalculateX(liquidity, sp, sa, sb));
        ApproxIf(c, "calculate_y", () => LiquidityMath.CalculateY(liquidity, sp, sa, sb));

        // Range bounds from amounts.
        ApproxIf(c, "calculate_a1", () => LiquidityMath.CalculateA1(liquidity, sp, y));
        ApproxIf(c, "calculate_a2", () => LiquidityMath.CalculateA2(sp, sb, x, y));
        ApproxIf(c, "calculate_b1", () => LiquidityMath.CalculateB1(liquidity, sp, x));
        ApproxIf(c, "calculate_b2", () => LiquidityMath.CalculateB2(sp, sa, x, y));

        // Ratio reconstructions (fed the oracle's true ratios, matching the reference's test()).
        ApproxIf(c, "calculate_c", () => LiquidityMath.CalculateC(p, Dec(c, "d_true"), x, y));
        ApproxIf(c, "calculate_d", () => LiquidityMath.CalculateD(p, Dec(c, "c_true"), x, y));

        // Inventory deltas as the price moves (whitepaper delta form).
        var move = c.GetProperty("price_move");
        if (move.ValueKind != JsonValueKind.Null)
        {
            var (deltaX, deltaY) = LiquidityMath.AmountDeltas(liquidity, sp, Dec(move, "sp1"), sa, sb);
            Approx(deltaX, Dec(move, "delta_x"), $"{name}.delta_x");
            Approx(deltaY, Dec(move, "delta_y"), $"{name}.delta_y");
        }
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void Decimal_sqrt_and_kernel_reproduce_liquidity_end_to_end(string name)
    {
        // Validates PriceMath.Sqrt (our deterministic decimal sqrt) plus the kernel end to end: deriving
        // the sqrt prices ourselves still lands on the oracle's liquidity within tolerance.
        var c = FindCase(name);
        var inputs = c.GetProperty("inputs");

        var sp = PriceMath.Sqrt(Dec(inputs, "p"));
        var sa = PriceMath.Sqrt(Dec(inputs, "a"));
        var sb = PriceMath.Sqrt(Dec(inputs, "b"));

        Approx(sp, Dec(c.GetProperty("sqrt"), "sp"), $"{name}.sqrt(p)");

        var liquidity = LiquidityMath.GetLiquidity(Dec(inputs, "x"), Dec(inputs, "y"), sp, sa, sb);
        Approx(liquidity, Dec(c, "liquidity"), $"{name}.liquidity (own sqrt)");
    }

    private static JsonElement FindCase(string name)
    {
        foreach (var c in Document.RootElement.GetProperty("cases").EnumerateArray())
        {
            if (c.GetProperty("name").GetString() == name)
            {
                return c;
            }
        }

        throw new InvalidOperationException($"Golden case '{name}' not found.");
    }

    private static decimal Dec(JsonElement parent, string property) => parent.GetProperty(property).GetDecimal();

    private static void ApproxIf(JsonElement c, string property, Func<decimal> actual)
    {
        var element = c.GetProperty(property);
        if (element.ValueKind == JsonValueKind.Null)
        {
            return; // undefined for this case (e.g. divide-by-zero branch) — nothing to assert.
        }

        Approx(actual(), element.GetDecimal(), $"{c.GetProperty("name").GetString()}.{property}");
    }

    private static void Approx(decimal actual, decimal expected, string label)
    {
        var tolerance = expected == 0m ? RelativeTolerance : RelativeTolerance * Math.Abs(expected);
        actual.Should().BeApproximately(expected, tolerance, "oracle value for {0}", label);
    }

    private static JsonDocument LoadDocument()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Golden", "fixtures.json");
        return JsonDocument.Parse(File.ReadAllText(path));
    }
}
