// <auto-generated />
using System;
using FollowAlpha.LP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FollowAlpha.LP.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616141450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainlinkFeedAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decimals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InWatchlist")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.AuditReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputDataHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("AuditReports");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DataWindowFromUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DataWindowToUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputDataHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Chain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RpcEnvVarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.DecisionAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DecisionLogEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecisionLogEntryId");

                    b.ToTable("DecisionAnnotations");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.DecisionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Capital")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExpectancyNet")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickLower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickUpper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Verdict")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("TenantId", "PoolId");

                    b.ToTable("DecisionLogEntries");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.DexProtocol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeeTiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionManagerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubgraphId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.ToTable("DexProtocols");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.IntentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DeclaredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesIntentRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("SupersedesIntentRecordId");

                    b.HasIndex("TenantId", "PositionId");

                    b.ToTable("IntentRecords");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Pool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DexProtocolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeTier")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InWatchlist")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickSpacing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token0AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token1AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainId");

                    b.HasIndex("DexProtocolId");

                    b.HasIndex("Token0AssetId");

                    b.HasIndex("Token1AssetId");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.PoolSnapshot", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AsOfUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentTick")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DayVolumeUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Liquidity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SqrtPriceX96")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tvl")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "PoolId", "AsOfUtc");

                    b.HasIndex("PoolId");

                    b.ToTable("PoolSnapshots");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpenedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickLower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickUpper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("WalletId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.PositionEvent", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TxHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogIndex")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount0")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount1")
                        .HasColumnType("TEXT");

                    b.Property<long>("BlockTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeesCollected0")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeesCollected1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GasCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiquidityDelta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickLower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickUpper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "ChainId", "TxHash", "LogIndex");

                    b.HasIndex("PoolId");

                    b.HasIndex("WalletId");

                    b.ToTable("PositionEvents");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.PriceBar", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpenTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Open")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "AssetId", "Resolution", "OpenTimeUtc");

                    b.HasIndex("AssetId");

                    b.ToTable("PriceBars");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.TickLiquiditySnapshot", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoolId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AsOfUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LiquidityGross")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiquidityNet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId", "PoolId", "AsOfUtc", "Tick");

                    b.HasIndex("PoolId");

                    b.ToTable("TickLiquiditySnapshots");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.AuditReport", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.DecisionAnnotation", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.DecisionLogEntry", null)
                        .WithMany()
                        .HasForeignKey("DecisionLogEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.DecisionLogEntry", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.DexProtocol", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Chain", null)
                        .WithMany()
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.IntentRecord", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowAlpha.LP.Application.Persistence.IntentRecord", null)
                        .WithMany()
                        .HasForeignKey("SupersedesIntentRecordId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Pool", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Chain", null)
                        .WithMany()
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowAlpha.LP.Application.Persistence.DexProtocol", null)
                        .WithMany()
                        .HasForeignKey("DexProtocolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowAlpha.LP.Application.Persistence.Asset", null)
                        .WithMany()
                        .HasForeignKey("Token0AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowAlpha.LP.Application.Persistence.Asset", null)
                        .WithMany()
                        .HasForeignKey("Token1AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.PoolSnapshot", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.Position", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowAlpha.LP.Application.Persistence.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.PositionEvent", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FollowAlpha.LP.Application.Persistence.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.PriceBar", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowAlpha.LP.Application.Persistence.TickLiquiditySnapshot", b =>
                {
                    b.HasOne("FollowAlpha.LP.Application.Persistence.Pool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
